# Generated by Django 2.2.5 on 2019-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20190920_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='anonymous', max_length=60),
        ),
    ]
